### PR TITLE
Static libs

### PR DESCRIPTION
**Pull request by geor-kasapidi**
### Checklist
- [x] All new and existing tests pass
- [x] I've read the [Contribution Guidelines](https://github.com/google/science-journal-ios/blob/master/CONTRIBUTING.md)

### Motivation and Context
Static libs usage decreases app startup time

### Description

1. removed `use_frameworks!` from podfile
2. updated project structure and build settings
3. removed custom module maps
4. moved generated protos into standalone framework
5. fixed tests (some tests were device and locale dependent)
6. added setup script which automatically installs protobuf and pods

### CODE REVIEW

**Comment by geor-kasapidi** [comment]
I signed it!

**Comment by taquitos** [comment]
Wow, I'm gonna have to take some time to review, thanks for putting this together. There are a few things that will prove challenging. Mainly, we have some restrictions around project structure that I'll have to outline. But will look into this 👍

**Comment by taquitos** [comment]
Thanks for the contribution 👋 There are a few things that will prove challenging with this PR, mainly things about how we package our App internally that require our OSS app to be a certain way. I'm going to spend some time going through this and will get back to you. We might need to split a few things up, so sit tight!

**Comment by taquitos** [comment]
Sorry, this got closed without explanation, I was correcting some previous commit authors during the pre-open source days.

Unfortunately, it looks like we can't accept this PR. We have a lot of internal tooling issues, dependency requirements, and project structure limitations. Also, this project is the base of our closed-source version, so there is some stuff happening that isn't visible. 

I wish we could accept it 😢

But, good news: I'm putting together a list of issues we want to solve, so soonish I'll have a bunch of clear cut things people can grab and work on.

Also, I wrote up an explanation around this: https://github.com/google/science-journal-ios/blob/master/CHANGE_LIMITATIONS.md

So sorry you spent time on this, hopefully your pain will save somebody else from spending the time changing stuff we can't accept now that we have the CHANGE_LIMITATIONS.md doc.

**Pull request closed without merging**
